Remove Anonlink Entity Service
data61/anonlink-client pull request #175
Opened 2022-11-10 04:45 UTC by nairs22

Remove Anonlink link Entity service which includes cli commands that uses Entity service - create, create, upload, etc. Update test cases,  README.md and other docs

2022-11-10 09:21 UTC, wilko77 requested changes
<img src="https://user-images.githubusercontent.com/3759021/201049928-0fa5feb1-c6b0-437c-b8f4-9f21ef4f9af8.png" width="100" />

- also remove the now obsolete dependencies
- The story of the CLI tutorial ends rather abruptly now. I think for now, we should just do the same as in the API tutorial, using anonlink api calls for doing the linkage. Everyone wants a happy ending.

2022-11-11 02:58 UTC, hardbyte approved these changes

2022-11-11 02:58 UTC, hardbyte commented on README.md
> + Identifying Information) locally using `anonlink hash` and generate candidate blocks locally to scale up record linkage
```suggestion
 Identifying Information) locally using `anonlink encode` and generate candidate blocks locally to scale up record linkage 
```

2022-11-21 02:48 UTC, nairs22 commented
This branch is redundant. please refer to branch: remove-entity-service-url

2022-11-21 02:48 UTC, closed without merging